name: Update CTF Tracker

on:
  schedule:
    
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Script
        run: python bot.py

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Mengubah username git ke nama Anda agar kontribusi tercatat lebih rapi
          git config --global user.name "Frigg1337"
          git config --global user.email "rrado2294@gmail.com"
          git add README.md
          
          # Memaksa commit meskipun tidak ada perubahan file agar mendapat kotak hijau
          git commit -m "🤖 Update jadwal CTF" --allow-empty
          
          # MEMPERBAIKI ERROR PUSH: Memasukkan GITHUB_TOKEN langsung ke URL push
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
